Update KPI from PXP to pipeline runs
meltano/handbook pull request #335
Opened 2022-08-30 16:44 UTC by tayloramurphy

2022-08-30 16:46 UTC, tayloramurphy commented
@pnadolny13 will you take an iteration on the implementation details?

2022-09-01 15:01 UTC, pnadolny13 commented
@tayloramurphy theres a definition of pipelines in https://handbook.meltano.com/data-team/metrics-and-definitions#pipeline that reflects the current state. Should I just put a cross reference there? Or were you looking for a different implementation using the active users definition we used in PxP i.e. >=7days old, 28 rolling window, etc.

2022-09-01 19:02 UTC, tayloramurphy commented
@pnadolny13 I'm actually fine to cross-link if the logic is accurate. I can make that change and then get Douwe to approve and merge.

2022-09-06 10:39 UTC, DouweM commented on src/_data-team/kpis.md
> +Meltano's primary strategic goal is to achieve product-market fit for Meltano as the DataOps Platform Infrastructure, with a particular focus on ELT workloads. Our primary metric for measuring progre
```suggestion
Meltano's primary strategic goal is to achieve product-market fit for Meltano as a data movement (EL+T) solution with 10X developer experience over alternatives. Our primary metric for measuring progress towards this goal is the number of pipelines run.
```

2022-09-06 10:40 UTC, DouweM requested changes
@tayloramurphy Changes look good, but it's time to restate the goal. Feel free to edit further.

2022-09-06 17:38 UTC, tayloramurphy commented
@DouweM accepted your change and I think it's good as is. Please merge if you agree.

2022-09-08 10:07 UTC, merged

2022-09-08 10:08 UTC, DouweM commented
@tayloramurphy Merged! Can you please share this in internal-announcements since it's a Data topic?

2022-09-08 16:19 UTC, tayloramurphy commented
Inviting discussion from the team in https://github.com/meltano/internal-data/discussions/21