Update support handbook
meltano/handbook pull request #363
Opened 2022-11-17 17:33 UTC by afolson

2022-11-17 17:36 UTC, afolson commented
@DouweM What's the current workflow for `security@` emails? Those no longer go to ZenDesk and I don't know who the DRI is.

2022-11-17 21:57 UTC, DouweM commented on src/_support/index.md
>  Emails to `security@meltano.com` also forward to Zendesk, and are automatically assigned to the Security group, which includes all current team members.
```suggestion
Emails to `security@meltano.com` also forward to HubSpot, and are automatically assigned the Security Issue category.
```

2022-11-17 22:01 UTC, DouweM commented on src/_support/index.md
> +We try to respond to issues and PRs created by the community within 24 hours. New PRs and issues across Meltano projects and the Singer ecosystem are posted to #singer-ecosystem-activity on Slack.
Activity on Singer tap/target repos goes into `#singer-ecosystem-activity`, but issues/PRs on the other Meltano projects (meltano/meltano, meltano/hub, meltano/sdk) does not. Those first two have their own channels (#meltano-repo-activity, #hub-repo-activity), but I don't think the SDK does, and those 2 channels are super noisy as they also include our team's activity, not just that by the community. Do we have a different process for those 3 repos we can document here? Or should we look into creating a new channel that only includes new community issues/PRs?

2022-11-17 22:02 UTC, DouweM commented
> @DouweM What's the current workflow for `security@` emails? Those no longer go to ZenDesk and I don't know who the DRI is.

@afolson Good point, they were being forwarded to me, but I just set them up to go into HubSpot as well and I've updated the PR. I still get email notifications for all new HubSpot tickets so I'll make sure they are processed.

2022-11-17 22:18 UTC, DouweM requested changes
Thanks Amanda, just a question about GH issues/PRs and a request to document the exact process we follow to hit these soft SLAs.

2022-11-17 22:18 UTC, DouweM commented on src/_support/index.md
> +Support on Slack is primarily provided by the community, but we strive to answer all questions within 24 hours. The [#support](https://meltano.slack.com/archives/C029CUM7ATD) Slack channel is where M
"we strive to answer all questions within 24 hours" makes sense as something to tell our users, which is one purpose of the handbook, but for internal purposes I think this needs to be more precise about the how and the who, so that there can be no confusion over who are responsible for keeping this promise to our community (as much as possible, responding in 24h already won't work over the weekends for example). 

I _think_ the process here is that you and Sven check the main support channels (that would be good to list explicitly) every morning, look for unanswered threads from yesterday, and either directly respond or post them into `#support` for other team members to pick up. 

As for `#support`, I think we need to make it explicit who are expected to monitor that for assists, so that the process doesn't break down there and we can explicitly communicate that to the people in question. One downside of using #support for assists is that it also gets HubSpot support messages (email, live chat) now, which engineers aren't expected to respond to, so they may get conditioned into ignoring an unread support channel because it's not always for them. It may be better to ask for assists in #internal-engineering instead where engs are more likely to find it organically, or to pipe HubSpot messages elsewhere.

I don't care so much about a specific process as making sure things don't fall through the cracks and we have the edge cases covered, so super open to suggestions!

2022-11-17 22:18 UTC, DouweM commented on src/_support/index.md
> +Emails to `support@meltano.com` forward to HubSpot so they can be triaged, assigned, and managed.
These should also be piped into #support like live chats are, but apparently that didn't happen to that email from S...N... at S... that we were discussing that earlier today... Still worth documenting that that's the intended process though. And that all of those are forwarded by email to both you and me (right?) and that one of us will handle them within 24h.

2022-12-14 20:04 UTC, DouweM requested changes

2022-12-14 20:04 UTC, DouweM commented on src/_support/index.md
> +The DevRel team tries to respond to issues and PRs created by the community within 24 hours. New PRs and issues across Meltano projects are posted to `#meltano-repo-activity` and `#hub-repo-activity`
I've created a new issue to create a `#sdk-repo-activity` channel as well: https://github.com/meltano/internal-general/issues/462, so we monitor all our official repos in Slack. All those channels are super noisy as they also include our team's activity, not just that by the community. Should we look into creating a new channel that only includes new community issues/PRs?

Also, would you mind documenting the process like you've done above? Sven indicated that he doesn't have bandwidth to monitor these, so if that works for you that'd be on you. I imagine it'd be a similar "every morning, respond to those from yesterday that didn't get a response from and eng or Taylor already, and ping the appropriate person".

2022-12-20 18:35 UTC, afolson commented
@DouweM I'm torn on this one. To do this properly I don't think it's enough to just answer questions. Part of this is clarifying the docs or adding troubleshooting info so that people won't have to reach out to us in the future. I don't think we have much time for that second step right now but I think it's critical to providing better support. Let's chat about it in our 1:1.

2022-12-23 17:08 UTC, afolson commented
Cbf to fix this merge conflict for a 4th time. Closing and reopening.

2022-12-23 17:08 UTC, closed without merging